# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='\u8bfe\u7a0b'),
        ),
    ]
