# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-19 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20180327_2256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '\u5ba2\u6237\u8868(\u5b66\u751f)', 'verbose_name_plural': '\u5ba2\u6237\u8868(\u5b66\u751f)'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '\u83dc\u5355', 'verbose_name_plural': '\u83dc\u5355'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': '\u7cfb\u7edf\u7528\u6237'},
        ),
        migrations.AddField(
            model_name='menu',
            name='url_type',
            field=models.SmallIntegerField(choices=[(0, 'alias'), (1, 'absolute_url')], default=0),
        ),
        migrations.AlterField(
            model_name='branch',
            name='addr',
            field=models.CharField(max_length=128, verbose_name='\u6821\u533a\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='\u6821\u533a\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='course',
            name='outline',
            field=models.TextField(verbose_name='\u5927\u7eb2'),
        ),
        migrations.AlterField(
            model_name='courserecord',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile', verbose_name='\u4e0a\u8bfe\u8001\u5e08'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile', verbose_name='\u5ba2\u6237\u7ecf\u7406'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(blank=True, to='crm.Tag', verbose_name='\u6807\u7b7e'),
        ),
        migrations.AlterField(
            model_name='customerfollowup',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile', verbose_name='\u8d26\u53f7'),
        ),
        migrations.AlterField(
            model_name='customerfollowup',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='\u5ba2\u6237'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='attendance',
            field=models.SmallIntegerField(choices=[(0, '\u5df2\u7b7e\u5230'), (1, '\u8fdf\u5230'), (2, '\u7f3a\u52e4'), (3, '\u65e9\u9000')], default=0, verbose_name='\u51fa\u52e4\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='course_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.CourseRecord', verbose_name='\u4e0a\u8bfe\u8bb0\u5f55'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='score',
            field=models.SmallIntegerField(choices=[(100, 'A+'), (90, 'A'), (85, 'B+'), (80, 'B'), (75, 'B-'), (70, 'C+'), (60, 'C'), (40, 'C-'), (-50, 'D'), (-100, 'COPY'), (0, 'N/A')], default=0, verbose_name='\u5206\u6570'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='\u6807\u7b7e\u540d'),
        ),
    ]
