# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_userprofile_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='\u5408\u540c\u540d\u79f0')),
                ('template', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.SmallIntegerField(choices=[(0, '\u8f6c\u4ecb\u7ecd'), (1, 'QQ\u7fa4'), (2, '\u5b98\u7f51'), (3, '\u767e\u5ea6\u63a8\u5e7f'), (4, '51CTO'), (5, '\u77e5\u4e4e'), (6, '\u5e02\u573a\u63a8\u5e7f')], verbose_name='\u5ba2\u6237\u6765\u6e90\u65b9\u5f0f'),
        ),
        migrations.AddField(
            model_name='classlist',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.ContractTemplate'),
        ),
    ]
