# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-28 22:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20180425_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stu_account',
            field=models.ForeignKey(blank=True, help_text='\u53ea\u6709\u5b66\u5458\u62a5\u540d\u540e\u65b9\u53ef\u4e3a\u5176\u521b\u5efa\u8d26\u53f7', null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='\u5173\u8054\u5b66\u5458\u8d26\u53f7'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='\u8bfe\u7a0b\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='course',
            name='outline',
            field=models.TextField(verbose_name='\u8bfe\u7a0b\u5927\u7eb2'),
        ),
        migrations.AlterField(
            model_name='course',
            name='period',
            field=models.PositiveSmallIntegerField(verbose_name='\u4e0a\u8bfe\u5468\u671f(\u6708)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='\u8bfe\u7a0b\u4ef7\u683c'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u9500\u552e'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='\u5ba2\u6237\u540d(qq)'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='course_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.CourseRecord', verbose_name='\u8bfe\u7a0b\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Enrollment', verbose_name='\u5b66\u751f\u4fe1\u606f'),
        ),
    ]
