# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-30 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20180428_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracttemplate',
            options={'verbose_name_plural': '\u5408\u540c\u7ba1\u7406'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_fuck_him_to_death', '\u5f04\u6b7b\u5c0f\u864e\u903c'), ('can_access_my_course', '\u53ef\u4ee5\u8bbf\u95ee\u6211\u7684\u8bfe\u7a0b'), ('can_access_customer_list', '\u53ef\u4ee5\u8bbf\u95ee\u5ba2\u6237\u5217\u8868'), ('can_access_customer_detail', '\u53ef\u4ee5\u8bbf\u95ee\u5ba2\u6237\u8be6\u7ec6'), ('can_access_studyrecords', '\u53ef\u4ee5\u8bbf\u95ee\u5b66\u4e60\u8bb0\u5f55\u9875\u9762'), ('can_access_homework_detail', '\u53ef\u4ee5\u8bbf\u95ee\u4f5c\u4e1a\u8be6\u60c5\u9875\u9762'), ('can_upload_homework', '\u53ef\u4ee5\u4ea4\u4f5c\u4e1a'), ('access_kingadmin_table_obj_detail', '\u53ef\u4ee5\u8bbf\u95eekingadmin\u6bcf\u4e2a\u8868\u7684\u5bf9\u8c61'), ('change_kingadmin_table_obj_detail', '\u53ef\u4ee5\u4fee\u6539kingadmin\u6bcf\u4e2a\u8868\u7684\u5bf9\u8c61'))},
        ),
    ]
