# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-08 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20180430_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('crm_table_list', '\u67e5\u770b\u6240\u6709table\u5217\u8868'), ('crm_table_list_view', '\u8bbf\u95ee\u4fee\u6539\u9875'), ('crm_table_list_change', '\u63d0\u4ea4\u4fee\u6539\u9875\u9762'), ('crm_table_obj_add_view', '\u8bbf\u95ee\u6dfb\u52a0\u6570\u636e\u9875'), ('crm_table_obj_add', '\u6dfb\u52a0\u6570\u636e'))},
        ),
    ]
